### ISSUE TITLE
interface for `registerIdentifiedUser` is `email` ... plugin uses `userEmail`?

### ISSUE THREAD

**Issue by spanning** [capacitor-community/intercom#22]
**Describe the bug**
interface for `registerIdentifiedUser` define email field as `email` ... plugin uses `userEmail`
```
let userEmail = call.getString("userEmail")
```

**Expected behavior**
Plugin.swift should use `email`

**Comment by abarax** [comment]
This is absolutely a bug, If I have time I'll try and put together a pull request.

**Comment by stewones** [comment]
please try again with 3.0.2
