### ISSUE TITLE
Capacitor 3 support

### ISSUE THREAD

**Issue by jongbonga** [capacitor-community/intercom#28]
**Is your feature request related to a problem? Please describe.**
Currently not being able to run on Capacitor 3

Getting `TypeError: undefined is not an object (evaluating 'IntercomPlugin.registerIdentifiedUser')`

**Describe the solution you'd like**
Hey @stewones Can we get Capacitor 3 support?

**Describe alternatives you've considered**
I have tried the [cordova-plugin-intercom](https://github.com/intercom/intercom-cordova) but it still get me the same error I got 13 months ago

**Comment by rajeshrapaka** [comment]
In Capacitor 3.0 plugins are obsolete. 
Hence getting this error: 
Compiling for iOS 11.0, but module 'Capacitor' has a minimum deployment target of iOS 12.0
Will there be an update for this? Please suggest.

**Comment by jongbonga** [comment]
@rejeshrapaka did you manage to make it work on Android for capacitor v3?

**Comment by spaghettiguru** [comment]
Any progress with this?

**Comment by jongbonga** [comment]
Hey @stewones any chance to find some time in your busy schedule to look into this? we will greatly appreciate

**Comment by rajeshrapaka** [comment]
> > In Capacitor 3.0 plugins are obsolete.
> > Hence getting this error:
> > Compiling for iOS 11.0, but module 'Capacitor' has a minimum deployment target of iOS 12.0
> > Will there be an update for this? Please suggest.
> 
> Did you manage to make it work on Android for capacitor v3?

unfortunately no @jongbonga. To meet the client's deadline I had to shift back to v2. Waiting for an update in future hopefully.

**Comment by roxteddy** [comment]
Hello there !

I was able to build and use Intercom plugin with Capacitor 3 on both iOS 14 and Android 11.

For iOS, simply change the plugin build target to iOS 12.x

For Android, I had to follow the step "Switch to automatic Android plugin loading" on https://capacitorjs.com/docs/updating/3-0#switch-to-automatic-android-plugin-loading

mind the `registerPlugin(PluginInMyApp.class);`

**Comment by jongbonga** [comment]
Hey @roxteddy , I tried to `import com.getcapacitor.community.intercom.IntercomPlugin` and `registerPlugin(IntercomPlugin.class)` but I'm getting `error: cannot find symbol Intercom.client().hideMessenger()` on Android.

it's working fine on iOS
