### ISSUE TITLE
Error using plugin in Andoird: Cannot read property 'registerIdentifiedUser'

### ISSUE THREAD

**Issue by sergiosanabria** [capacitor-community/intercom#29]
**Error using plugin in Andoird**

When I want to use:

`import { Intercom } from "@capacitor-community/intercom";`

`this.platform.ready().then(() => {`
    `Plugins.IntercomPlugin.registerIdentifiedUser({userId:'xxx'})`
`})`

**Throw the following error only on Android.**

`Cannot read property 'registerIdentifiedUser'`

On iOS it works fine.

*ionic info*

Ionic:

   Ionic CLI                     : 5.4.9 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 5.0.3
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.3.0
   @capacitor/core : 2.3.0

Cordova:

   Cordova CLI       : 8.0.0
   Cordova Platforms : android 8.0.0, browser 5.0.4
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 11 other plugins)

Utility:

   cordova-res : 0.15.1 (update available: 0.15.3)
   native-run  : not installed

System:

   Android SDK Tools : 26.1.1 (/Users/sergiosanabria/Library/Android/sdk/)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.2
   NodeJS            : v12.18.3 (/Users/sergiosanabria/.nvm/versions/node/v12.18.3/bin/node)
   npm               : 6.14.6
   OS                : macOS
   Xcode             : Xcode 12.3 Build version 12C33

**Comment by jongbonga** [comment]
For some reason, mine works fine on capacitor v2 [but not on v3](#28 )

**Comment by stewones** [comment]
please have a try on latest?
make sure to review the [breaking changes](https://github.com/capacitor-community/intercom#breaking-changes-from-capacitor-v2-to-v3)
