### ISSUE TITLE
'GCDWebServerDataRequest.h' file not found capacitor 3 intercom error

### ISSUE THREAD

**Issue by Hambat** [capacitor-community/intercom#44]
Updated the capacitor and @capacitor-community/intercom to 3v, i get this error ('GCDWebServerDataRequest.h' file not found)
if remove the intercom everything is ok

Help please
<img width="1012" alt="Screenshot 2021-10-12 at 8 40 18 PM" src="https://user-images.githubusercontent.com/8243013/137005031-147a7c78-cc92-4607-82d7-a7da1a5f3f94.png">
..

**Comment by stewones** [comment]
That's odd. Can you provide a minimal reproducible example?

What's the file name in xcode? Your screenshot is cropping the top

**Comment by Hambat** [comment]
<img width="1073" alt="Screenshot 2021-10-13 at 11 10 32 AM" src="https://user-images.githubusercontent.com/8243013/137093822-8f555dd8-87e8-4a3e-acf2-ebc5d23930d7.png"
<img width="492" alt="Screenshot 2021-10-13 at 11 12 55 AM" src="https://user-images.githubusercontent.com/8243013/137093986-a86f4a21-f047-46d3-a017-bc6d11addea6.png">
>

**Comment by Hambat** [comment]
@stewones Thank you very much 🍀😎
