### ISSUE TITLE
iOS Bug [Intercom] ERROR - Cannot present Messenger because no user is registered - you need register a user first 

### ISSUE THREAD

**Issue by Hambat** [capacitor-community/intercom#45]
After await Intercom.registerIdentifiedUser({ email: data.email, userId: data.id }); i get this [Intercom] ERROR , but user is registered on android everything is ok

[Intercom] ERROR - Cannot present Messenger because no user is registered - you need register a user first -> Showing fallback error screen. Debug info: { has_identity: 1, has_user: 1, has_user_identification: 0 }

**Comment by stewones** [comment]
Please try on v4
