### ISSUE TITLE
Using FCM token in iOS breaks push notifications for intercom

### ISSUE THREAD

**Issue by AidenTate** [capacitor-community/intercom#49]
**Describe the bug**
On iOS, If you fetch the firebase FCM token instead of the raw APNS token and use that for the capacitorDidRegisterForRemoteNotifications listener, push notifications do not work.

**To Reproduce**

1. follow guide for installing and using @capacitor/push-notifications
2. follow guide for installing and using @capacitor-community/intercom
3. Use the following code in AppDelegate, as mentioned in the capacitor [ push notifications guide ](https://capacitorjs.com/docs/guides/push-notifications-firebase)
```swift 
func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        Messaging.messaging().apnsToken = deviceToken
        NotificationCenter.default.post(name: .capacitorDidRegisterForRemoteNotifications, object: deviceToken)
        Messaging.messaging().token(completion: { (token, error) in
            if let error = error {
                NotificationCenter.default.post(name: .capacitorDidFailToRegisterForRemoteNotifications, object: error)
            } else if let token = token {
                NotificationCenter.default.post(name: .capacitorDidRegisterForRemoteNotifications, object: token)
            }
        })
    }
```
 
**To Fix**
I have resolved this by adding the following line in my AppDelegate didRegisterForRemoteNotificationsWithDeviceToken method but I am not sure if this is the ideal solution as I do not know a lot of Swift.
```swift func 
Intercom.setDeviceToken(deviceToken)
```
So now the function looks like this and I can receive both APNS notifications from Intercom and FCM notifications from firebase.
```swift 
  func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        Intercom.setDeviceToken(deviceToken)
        Messaging.messaging().apnsToken = deviceToken
        NotificationCenter.default.post(name: .capacitorDidRegisterForRemoteNotifications, object: deviceToken)
        Messaging.messaging().token(completion: { (token, error) in
            if let error = error {
                NotificationCenter.default.post(name: .capacitorDidFailToRegisterForRemoteNotifications, object: error)
            } else if let token = token {
                NotificationCenter.default.post(name: .capacitorDidRegisterForRemoteNotifications, object: token)
            }
        })
    }
```

**Smartphone:**
 - iPhone 12: [e.g. iPhone6]
 - OS: 15.1.1

**Comment by stewones** [comment]
sounds like an edge case, great solution tho. mind to doc in README and open a PR?

**Comment by stewones** [comment]
intercom registration is done automatically by the plugin, you shouldn't have to do it manually in your app delegate.
