### ISSUE TITLE
CocoaPods could not find compatible versions for pod "Intercom" on 3.0.2

### ISSUE THREAD

**Issue by jongbonga** [capacitor-community/intercom#54]
**Describe the bug**
After updating to 3.0.2, Pod install fails with:

```
[capacitor] ✖ Updating iOS native dependencies with pod install - failed!
[capacitor] ✖ update ios - failed!
[capacitor] [error] Analyzing dependencies
[capacitor]         [!] CocoaPods could not find compatible versions for pod "Intercom":
[capacitor]         In Podfile:
[capacitor]         CapacitorCommunityIntercom (from `../../node_modules/@capacitor-community/intercom`) was resolved to 3.0.2, which depends on
[capacitor]         Intercom (~> 11.2.0)
[capacitor]         
[capacitor]         Specs satisfying the `Intercom (~> 11.2.0)` dependency were found, but they required a higher minimum deployment target.
```

**To Reproduce**
```
npm I @capacitor-community/intercom@.3.0.2
npx cap sync ios
```

**Comment by jongbonga** [comment]
After updating the `podfile.lock` manually, I get the warning bellow

`[!] The platform of the target `App` (iOS 12.0) may not be compatible with `Intercom (11.2.0)` which has a minimum requirement of iOS 13.0.`

Can we have the minimum requirement set to `12.0`

**Comment by walfridosp** [comment]
Hi @jongbonga, I had the same issue, the temporary solution I found is to downgrade to:
 `
  s.dependency 'Intercom', '~> 10.0'
`
in CapacitorCommunityIntercom.podspec

hope this helps
