### ISSUE TITLE
Error while registerIdentifiedUser 

### ISSUE THREAD

**Issue by git-mwayz** [capacitor-community/intercom#69]
**Error while calling registerIdentifiedUser**
[Intercom] ERROR - Tried to update user but there was a network error (401) - Request failed: unauthorized (401)

**Desktop (please complete the following information):**
 - OS: MAC
 - XCODE
 - Version [13.4.1]

**Smartphone (please complete the following information):**
 - Device: [iPhone7]
 - OS: [1515.6]

**Comment by choffmeyer** [comment]
same issue here.. ios doesn't seem to want to update data on intercom but android works fine.  not much configuration here so not sure what to tinker with?

**Comment by stewones** [comment]
v4 released, it adds support for cap 4 and intercom 13+
