### ISSUE TITLE
IOS Intercom.registerUser does not exist

### ISSUE THREAD

**Issue by brennanbatalla** [capacitor-community/intercom#70]
**Describe the bug**
I have a React + Capacitor app. I had installed this capacitor plugin as the directions instruct. For Android, everything works perfectly, for IOS, the build fails because of the error `Type 'Intercom' has no member 'registerUser'`

**Expected behavior**
Build completes and am able to run it successfully. 

**Screenshots**
<img width="1019" alt="Screen Shot 2022-09-20 at 7 52 17 PM" src="https://user-images.githubusercontent.com/6547415/191396441-10cc141c-562a-4c47-9dd1-2a7c4931c59c.png">

**Additional context**
After `npx cap doctor`

```
Latest Dependencies:

  @capacitor/cli: 4.2.0
  @capacitor/core: 4.2.0
  @capacitor/android: 4.2.0
  @capacitor/ios: 4.2.0

Installed Dependencies:

  @capacitor/cli: 4.2.0
  @capacitor/core: 4.2.0
  @capacitor/android: 4.2.0
  @capacitor/ios: 4.2.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

**Comment by maxnowack** [comment]
I think this is because 45f170392d47e4f56a54b2b771620196206a49da removes the dependency version of the `Intercom` pod completely. Therefore, it was upgraded to `v13` which has some [breaking changes](https://developers.intercom.com/installing-intercom/docs/migrating-to-v13).
A possible fix could be to assign a version limit to the `Intercom` dependency:
````
  s.dependency 'Intercom', '<= 12'
````

**Comment by stewones** [comment]
v4 released, it adds support for cap 4 and intercom 13+

**Comment by willgardner9** [comment]
Hi, I'm still seeing this issue on `@capacitor-community/intercom": "^4.0.0`

<img width="613" alt="Screenshot 2022-10-03 at 15 53 53" src="https://user-images.githubusercontent.com/57688524/193608488-61cf7577-8adb-4bfa-b445-612f86a94c74.png">

Let me know if there's any more info I can supply to help! Appreciate all the work on this package 👍

**Comment by maxnowack** [comment]
@willgardner9 have you maybe missed `npx cap sync`?

**Comment by willgardner9** [comment]
Hi @maxnowack, I've not missed `npx cap sync` sadly -- for full context, here's the steps I've taken to try and resolve:

1. Delete `node_modules`
2. Run a fresh install of `npm i`
3. Run `npx cap sync` (*logs below)
4. Attempt to build with `ionic capacitor build ios`

```
npx cap sync
✔ Copying web assets from www to android/app/src/main/assets/public in 603.79ms
✔ Creating capacitor.config.json in android/app/src/main/assets in 595.83μs
✔ copy android in 632.96ms
✔ Updating Android plugins in 5.75ms
[info] Found 14 Capacitor plugins for android:
       @capacitor-community/firebase-crashlytics@1.0.0
       @capacitor-community/intercom@4.0.0
       @capacitor/app@4.0.1
       @capacitor/browser@4.0.1
       @capacitor/clipboard@4.0.1
       @capacitor/haptics@4.0.1
       @capacitor/keyboard@4.0.1
       @capacitor/preferences@4.0.1
       @capacitor/push-notifications@4.1.0
       @capacitor/share@4.0.1
       @capacitor/status-bar@4.0.1
       @capacitor/storage@1.2.5
       capacitor-native-biometric@3.1.1
       capacitor-rate-app@2.0.0
✔ update android in 64.01ms
✔ Copying web assets from www to ios/App/App/public in 597.02ms
✔ Creating capacitor.config.json in ios/App/App in 433.33μs
✔ copy ios in 611.07ms
✔ Updating iOS plugins in 5.96ms
[info] Found 14 Capacitor plugins for ios:
       @capacitor-community/firebase-crashlytics@1.0.0
       @capacitor-community/intercom@4.0.0
       @capacitor/app@4.0.1
       @capacitor/browser@4.0.1
       @capacitor/clipboard@4.0.1
       @capacitor/haptics@4.0.1
       @capacitor/keyboard@4.0.1
       @capacitor/preferences@4.0.1
       @capacitor/push-notifications@4.1.0
       @capacitor/share@4.0.1
       @capacitor/status-bar@4.0.1
       @capacitor/storage@1.2.5
       capacitor-native-biometric@3.1.1
       capacitor-rate-app@2.0.0
✔ Updating iOS native dependencies with pod install in 3.42s
✔ update ios in 3.44s
✔ copy web in 6.17ms
✔ update web in 346.79μs
```

Let me know if there's anything you'd like me to try out! Thanks for your help! 👌
