### ISSUE TITLE
iOS Type 'Intercom' has no member 'loginUser' / 'loginUnidentifiedUser'

### ISSUE THREAD

**Issue by willgardner9** [capacitor-community/intercom#73]
**Describe the bug**
Attempting to build your Capacitor iOS project with `@capacitor-community/intercom` installed fails due to the `Type 'Intercom' has no member....` errors.

**To Reproduce**
1. `npm install @capacitor-community/intercom`
2. `npx cap sync`
3. Attempt to build your iOS project

**Expected behavior**
The build should succeed.

**Screenshots**
[Link to XCode error here.](https://user-images.githubusercontent.com/57688524/193608488-61cf7577-8adb-4bfa-b445-612f86a94c74.png)

**Additional context**
I have created a fork of this repo of the steps I took to get the build to succeed, [which you can view here](https://github.com/willgardner9/intercom/commit/6e66d122d89fb07fb93a5087799ead1e648f7478).

I've never written Swift before so I haven't handled any errors / might have made some other errors -- but I'm more than happy to spend some time doing this if it will help get this merged into this repo.

This issue was mentioned in [this closed issue](https://github.com/capacitor-community/intercom/issues/70), I mentioned it in that issue, but now that I've forked an example of how to fix I think it's okay to create a new issue. If not, please feel free to close & apologies for the spam 👍

Thanks to all the contributors and maintainers for this wonderful Capacitor plugin! 😄 

**Before:**
`
Intercom.loginUser(with: attributes)...
`

**After:**
`
Intercom.registerUser(withEmail: attributes.email!)
`

**Comment by stewones** [comment]
the latest plugin version is working fine for me. I've just updated a client app.

what's the intercom version running on your ios client? it must be v13/v14

you can try to `pod update` on ios/App folder

**Comment by choffmeyer** [comment]
Same issue using the latest 4.0.1 and also tried pod update with not success.

**Comment by choffmeyer** [comment]
I guess ionic cap build ios isn't enough.. you have to run npx cap sync
