### ISSUE TITLE
Capacitor 5 compatibility

### ISSUE THREAD

**Issue by Paso** [capacitor-community/intercom#85]
**Is your feature request related to a problem? Please describe.**
A Capacitor 5 project with this plugin won't build on android because the package namespace/id being moved from AndroidManifest.xml to build.gradle. See https://capacitorjs.com/docs/next/updating/plugins/5-0

**Describe the solution you'd like**
A Capacitor 5 compatible release

**Comment by brennanbatalla** [comment]
+1

**Comment by Paso** [comment]
Capacitor 5.0.0 has been released now.

**Comment by cwoebker** [comment]
I just created a PR with the changes at #86.
